name: flake8-async CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools tox
        python -m tox --notest --recreate -e check
    - name: Run checks
      run: |
        python -m tox -e check
        git diff --exit-code

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools tox
        python -m tox --notest --recreate -e test
    - name: Run tests
      run: python -m tox -e test -- -n auto

  release:
    runs-on: ubuntu-latest
    needs: [check, test]
    if: github.repository == 'cooperlees/flake8-async' &&  github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Install tools
      run: python -m pip install --upgrade pip setuptools wheel twine
    - name: Upload new release
      env:
        TWINE_USERNAME: '__token__'
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: python setup.py sdist bdist_wheel && twine upload --skip-existing dist/*
